routingRules:
  - version: "2.0.0"
    targetType: "bpp"
    endpoints:
      - select
      - init
      - confirm
      - status
      - cancel
      - support
      - track
      - update
      - rate
  - version: "2.0.0"
    targetType: "url"
    target:
      url: "http://168.144.146.178:8080/receive"
    endpoints:
      - discover
