routingRules:
  - version: "2.0.0"
    targetType: "bap"
    endpoints:
      - on_discover
      - on_select
      - on_init
      - on_confirm
      - on_status
      - on_cancel
      - on_support
      - on_track
      - on_update
      - on_rate
  - version: "2.0.0"
    targetType: "url"
    target:
      url: "http://168.144.146.178:8080/receiver/catalog"
    endpoints:
      - push
