routingRules:
  - version: "2.0.0"
    targetType: "bpp"
    endpoints:
      - select
      - init
      - confirm
      - status
      - cancel
      - support
      - track
      - update
      - rate
  - version: "2.0.0"
    targetType: "url"
    target:
      url: "http://discover.168.144.146.178.sslip.io/receiver"
    endpoints:
      - discover
